#!/usr/bin/env python3

import asyncio
import sys

import click
import websockets


@asyncio.coroutine
def send(message):
    websocket = yield from websockets.connect('ws://localhost:30002/')
    try:
        yield from websocket.send(message)
    finally:
        yield from websocket.close()

@click.command()
@click.option('--command', type=click.Choice(['W','U','N']), default='W')
@click.argument('input', type=click.File('r'))
def main(command, input):
    text = input.read()
    asyncio.get_event_loop().run_until_complete(send(command+text))

if __name__ == "__main__":
    main()
